### ISSUE TITLE
Crash in OSX after a minute of use of mic

### ISSUE THREAD

**Issue by dfcreative** [audio-lab/gl-waveform#5]
https://twitter.com/Xavier_Ho/status/767263851393880068

That happens with soundcloud stream also.

**Comment by Spaxe** [comment]
Thanks for reporting this. The only reliable thing so far is that if you leave it for a while, it will definitely stop. No errors in console unfortunately.

Are the sources for `gh-pages` available for testing also?

**Comment by dfcreative** [comment]
It has wrong deps now, I will fix tomorrow. It has no-webworker mode, which does not crash. I think I will ping webworker to detect whether it is dead, and if it is, just recreate it. Though I have another, really stupid guess... Might be I just badly slice the data after a minute. Anyways will make all beautiful tomorrow, now sleep

**Comment by dfcreative** [comment]
Should be fixed.

**Comment by Spaxe** [comment]
Thanks, appears to be fixed on my end too!
